spring:
    datasource:
        url: jdbc:mysql://localhost:3306/recipe_app_prod_db
        username: recipe_app_prod_user
        password: pass #this should be passed by enviroment variable
    jpa:
        hibernate:
            ddl-auto: validate # tell hibernate to validate data base schema on startup
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        show-sql: false # in prod we do NOT whant to see the sql queries in the log