spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/recipe_app_dev_db
        username: recipe_app_dev_user
        password: pass #this should be passed by enviroment variable
    jpa:
        hibernate:
            ddl-auto: validate # tell hibernate to validate data base schema on startup
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        show-sql: true # in dev we whant to see the sql queries in the log
#        properties:
#            # instruct hibernate to create schema DDL in recipe_database_schema_create.sql
#            javax:
#                persistence:
#                    schema-generation:
#                        create-source: metadata
#                        scripts:
#                            action: create
#                            create-target: recipe_database_schema_create.sql
                            