# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    #image: mysql:5.7
    image: mysql:8.0.30-debian
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      #MYSQL_DATABASE: pet_clinic

    ports:
      - 3306:3306

    volumes:
      - ./db_data:/var/lib/mysql


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080